### 1.3.8.3 Broadcasting

In [1]:
import numpy as np

In [2]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [3]:
b = np.array([0, 1, 2])

In [4]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

在学习broadcasting之前，我们其实早已用过它了:

In [5]:
a = np.ones((4, 5))

In [6]:
a[0] = 2

In [7]:
a

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

下面是一个常用技巧:

In [8]:
a = np.arange(0, 40, 10)

In [9]:
a.shape

(4,)

In [10]:
a = a[:, np.newaxis]
a.shape

(4, 1)

In [11]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [12]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [13]:
x, y = np.ogrid[0:5, 0:5]
x, y

(array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]]))

In [14]:
x.shape, y.shape

((5, 1), (1, 5))

In [15]:
distance = np.sqrt(x **2 + y ** 2)

In [16]:
distance

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425]])

In [17]:
x, y = np.mgrid[0:4, 0:4]

In [18]:
x

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [19]:
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

### 1.3.8.4. 数组形状操作

#### 1.3.8.4.1. 扁平化

In [20]:
a = np.array([[1,2,3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [21]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

#### 1.3.8.4.2. 整形

In [25]:
a.shape

(2, 3)

In [26]:
b = a.ravel()
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a.reshape((2, -1))  # (-1)表示相应的维数由程序推断

array([[1, 2, 3],
       [4, 5, 6]])

#### 1.3.8.4.3. 添加维度

In [2]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [3]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [4]:
z[np.newaxis, :]

array([[1, 2, 3]])

#### 1.3.8.4.4 维度shuffling

In [5]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [6]:
a[0, 2, 1]

5

In [7]:
b = a.transpose(1, 2, 0)

In [8]:
b.shape

(3, 2, 4)

In [9]:
b[2, 1, 0]

5

In [10]:
b[2, 1, 0] = -1

In [11]:
a[0, 2, 1]

-1

#### 1.3.8.4.5. 改变尺寸

In [12]:
a = np.arange(4)

In [13]:
a.resize((8,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

### 1.3.8.5. 数据排序

In [16]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)

In [17]:
b

array([[3, 4, 5],
       [1, 1, 2]])

In [18]:
a.sort(axis=0)

In [19]:
a

array([[1, 2, 1],
       [4, 3, 5]])

In [20]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)

In [21]:
j

array([2, 3, 1, 0])

In [22]:
a[j]

array([1, 2, 3, 4])

In [23]:
j_max = np.argmax(a)

In [24]:
j_min = np.argmin(a)

In [25]:
j_max, j_min

(0, 2)

## 1.3.9. 数组内容进阶
### 1.3.9.1. 更多数据类型
#### 1.3.9.1.1. Casting

In [26]:
np.array([1, 2, 3]) + 1.5

array([ 2.5,  3.5,  4.5])

赋值永远不会改变数据类型！:

In [27]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [28]:
a[0] = 1.6   # <-- 浮点型被截断为整型

In [29]:
a

array([1, 2, 3])

- 强制cast

In [30]:
a = np.array([1.7, 1.2, 1.6])

In [31]:
b = a.astype(int)  # <-- 截断为整型

In [32]:
b

array([1, 1, 1])

- 舍入为整数

In [33]:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [34]:
b = np.around(a)

In [35]:
b

array([ 1.,  2.,  2.,  2.,  4.,  4.])

In [36]:
c = np.around(a).astype(int)

In [37]:
c

array([1, 2, 2, 2, 4, 4])

#### 1.3.9.1.2. 不同数据类型的大小

### 1.3.9.2. 结构化数据类型

### 1.3.9.3. maskedarray: 处理（或传递）缺失信息

In [38]:
x = np.ma.array([1, 2, 3, 4], mask=[0, 1, 0, 1])

In [39]:
x

masked_array(data = [1 -- 3 --],
             mask = [False  True False  True],
       fill_value = 999999)

In [40]:
y = np.ma.array([1, 2, 3, 4], mask=[0, 1, 1, 1])

In [41]:
y

masked_array(data = [1 -- -- --],
             mask = [False  True  True  True],
       fill_value = 999999)

In [42]:
x + y

masked_array(data = [2 -- -- --],
             mask = [False  True  True  True],
       fill_value = 999999)

In [43]:
np.ma.sqrt([1, -1, 2, -2])

masked_array(data = [1.0 -- 1.4142135623730951 --],
             mask = [False  True False  True],
       fill_value = 1e+20)